# Generated by Django 4.2.5 on 2024-03-23 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_event_licence_plate_event_place_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='place_name',
            new_name='place',
        ),
        migrations.AddField(
            model_name='event',
            name='assigned_ps',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
